/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Circle011_EyeFire_0.geometry} material={nodes.Circle011_EyeFire_0.material} />
            <mesh geometry={nodes.Circle011_SerpentBake_0.geometry} material={materials.SerpentBake} />
          </group>
          <group position={[-1018.2, -380.53, 1332.67]} rotation={[-1.05, 0.72, -0.08]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Hide003_Boat2Bake_0.geometry} material={materials.Boat2Bake} />
            <mesh geometry={nodes.Hide003_EyeFire_0.geometry} material={nodes.Hide003_EyeFire_0.material} />
          </group>
          <group position={[349.57, 32.32, 176.64]} rotation={[-1.73, -0.23, -2.65]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Keel002_Boat1Bake_0.geometry} material={materials.Boat1Bake} />
            <mesh geometry={nodes.Keel002_EyeFire_0.geometry} material={nodes.Keel002_EyeFire_0.material} />
          </group>
          <group position={[0, 27.07, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 170.02]}>
            <mesh geometry={nodes.Plane044_WaterBake_0.geometry} material={materials.WaterBake} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rock021_RockBake_0.geometry} material={materials.RockBake} />
          </group>
          <group scale={100}>
            <mesh
              geometry={nodes.VikingShipObjects001_Objects_0.geometry}
              material={nodes.VikingShipObjects001_Objects_0.material}
            />
            <mesh
              geometry={nodes.VikingShipObjects001_Objects_0001.geometry}
              material={nodes.VikingShipObjects001_Objects_0001.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
